# Array creation routines

In [3]:
import numpy as np 

Ones and zeros

In [3]:
# 1: Create a new array of 2*2 integers, without initializing entries.

In [8]:
arr = np.zeros((2,2), dtype = int)
print(arr)

[[0 0]
 [0 0]]


In [ ]:
# 2: 
# Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.
# Output : array([[1, 2, 3],
#                 [4, 5, 6]])

In [12]:
X = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print(X)
newarr = X.copy()
print(newarr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 3: Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [4]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4: Create a new array of 3*2 float numbers, filled with ones.

In [8]:
x4 = np.ones((3,2), dtype= np.float64)
print(x4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# 5: Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.
x = np.arange(4, dtype=np.int64)
newx = np.ones(x.shape, dtype = np.int64)
newx2 = np.ones_like(x)
print(newx)
print(newx2)

[1 1 1 1]
[1 1 1 1]


In [12]:
# 6: Create a new array of 3*2 float numbers, filled with zeros.

In [14]:
x = np.zeros((3,2), dtype = np.float64)
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
# 7: Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [21]:
x = np.arange(4, dtype = np.int64)
print(x)
newx = np.zeros(x.shape, int)
print(newx)
newx2 =np.zeros_like(x)
print(newx2)

[0 1 2 3]
[0 0 0 0]
[0 0 0 0]


In [22]:
# 8: Create a new array of 2*5 uints, filled with 6.

In [23]:
arr = np.full((2,5),6)
print(arr)

[[6 6 6 6 6]
 [6 6 6 6 6]]


In [24]:
# 9: Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [26]:
x = np.arange(4,dtype = np.int64)
print(x)
newx = np.full_like(x, 6)
print(newx)

[0 1 2 3]
[6 6 6 6]
